fonctionTab.o: ../librairie/tri/fonctionTab.c ../librairie/tri/fonctionTab.h
	gcc -c ../librairie/tri/fonctionTab.c -o fonctionTab.o

tri-tableau.o: ../librairie/tri/tri-tableau.c ../librairie/tri/tri-tableau.h fonctionTab.o
	gcc -c ../librairie/tri/tri-tableau.c -o tri-tableau.o
