fonctionTab.o: ../librairie/tableau/fonctionTab.c ../librairie/tableau/fonctionTab.h
	gcc -c ../librairie/tableau/fonctionTab.c -o fonctionTab.o

tri-tableau.o: ../librairie/tableau/tri-tableau.c ../librairie/tableau/tri-tableau.h fonctionTab.o
	gcc -c ../librairie/tableau/tri-tableau.c -o tri-tableau.o
